### ISSUE TITLE
Any reason not to exclude the /tasks dir when running the build command (copy)?

### ISSUE THREAD

**Issue by jtsternberg** [10up/generator-wp-make#100]
the /tasks dir is specific to Grunt, and I imagine would have no need in a build/release version.

**Comment by lkwdwrd** [comment]
Hey @jtsternberg, thanks for reaching out!

I agree with you it should be excluded in the build task. As it stands WP-Make is undergoing a 1.0 rewrite, so we're not sinking engineering time into updates to the pre-1.0 version at this time. I'd be happy to accept a PR with this update, though, and get it pushed out to NPM. We're probably a couple of months to a 1.0, due to the time the team has to sink in around other client work. The timeline here could even stretch longer, it will all depend on how much engineering time we can spend on the project.
